(() => {
  const STORAGE_KEY='intercvl-zese-atelier-ia-v1';
  const roles=['🧪 Pilote IA','📝 Rédacteur','🔎 Observateur critique','🗣️ Porte-parole'];
  const emptyState=()=>({groupName:'',step:0,team:Array.from({length:4},(_,i)=>({name:'',school:'',role:roles[i]})),fields:{},ranges:{m1_ai:50,m2_ai:50,m3_ai:50,d_speed:3,d_eval:3,d_integrate:3},checks:{},storyboard:Array.from({length:4},()=>({scene:'',prompt:''})),oral:''});
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function load(){try{return {...emptyState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return emptyState()}}
  let state=load(); state.team ||= emptyState().team; state.fields||={}; state.ranges||={}; state.checks||={}; state.storyboard||=emptyState().storyboard;
  let activeStep=Number(state.step||0),timerId=null,timerRunning=false,timerSeconds=600;
  const durationByStep={0:600,1:600,2:600,3:600,4:900,5:900};
  function save(show=true){state.step=activeStep;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show){const el=$('#saveStatus');if(el){el.textContent='✓ Sauvegardé sur cet appareil';setTimeout(()=>el.textContent='💾 Sauvegarde locale active',1100)}}}
  function toast(icon,title,text){const t=$('#rotationToast');t.querySelector('.toast-icon').textContent=icon;t.querySelector('strong').textContent=title;t.querySelector('span').textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4200)}

  $('#groupName').value=state.groupName||''; $('#groupName').addEventListener('input',e=>{state.groupName=e.target.value;save()});
  function go(step){activeStep=Number(step);$$('.panel').forEach(p=>p.classList.toggle('visible',Number(p.dataset.panel)===activeStep));$$('.step').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===activeStep));resetTimer();save(false);window.scrollTo({top:0,behavior:'smooth'})}
  $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go))); $$('.step').forEach(b=>b.addEventListener('click',()=>go(b.dataset.step)));

  function renderTeam(){const box=$('#roleGrid');box.innerHTML=state.team.map((p,i)=>`<article class="role-card"><div class="role-number">${i+1}</div><label>Prénom<input data-team-name="${i}" value="${esc(p.name)}" placeholder="Prénom"></label><label>Établissement<input data-team-school="${i}" value="${esc(p.school)}" placeholder="Ville / établissement"></label><label>Rôle<select data-team-role="${i}">${roles.map(r=>`<option ${p.role===r?'selected':''}>${r}</option>`).join('')}</select></label></article>`).join('');$$('[data-team-name]').forEach(el=>el.addEventListener('input',()=>{state.team[Number(el.dataset.teamName)].name=el.value;save()}));$$('[data-team-school]').forEach(el=>el.addEventListener('input',()=>{state.team[Number(el.dataset.teamSchool)].school=el.value;save()}));$$('[data-team-role]').forEach(el=>el.addEventListener('change',()=>{state.team[Number(el.dataset.teamRole)].role=el.value;save()}))}
  renderTeam();
  $('#autoRoles').addEventListener('click',()=>{const shuffled=[...roles].sort(()=>Math.random()-.5);state.team.forEach((p,i)=>p.role=shuffled[i]);save();renderTeam();toast('🎲','Rôles répartis','Vous pouvez encore les modifier manuellement.')});
  $('#clearTeam').addEventListener('click',()=>{state.team=emptyState().team;save();renderTeam()});

  $$('[data-field]').forEach(el=>{const k=el.dataset.field;if(state.fields[k]!=null)el.value=state.fields[k];el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{state.fields[k]=el.value;save()})});
  $$('[data-range]').forEach(el=>{const k=el.dataset.range;if(state.ranges[k]!=null)el.value=state.ranges[k];const render=()=>{$$(`[data-range-out="${k}"]`).forEach(o=>o.textContent=el.value);$$(`[data-human-out="${k}"]`).forEach(o=>o.textContent=100-Number(el.value));};render();el.addEventListener('input',()=>{state.ranges[k]=Number(el.value);render();save()})});

  function renderStoryboard(){const box=$('#storyboard');box.innerHTML=state.storyboard.map((s,i)=>`<article class="story-card"><div class="story-index">PLAN ${i+1}</div><label>Ce qu'on voit<textarea data-story-scene="${i}" placeholder="Décrivez la scène…">${esc(s.scene)}</textarea></label><label>Prompt image / vidéo<textarea data-story-prompt="${i}" placeholder="Prompt utilisé…">${esc(s.prompt)}</textarea></label></article>`).join('');$$('[data-story-scene]').forEach(el=>el.addEventListener('input',()=>{state.storyboard[Number(el.dataset.storyScene)].scene=el.value;save()}));$$('[data-story-prompt]').forEach(el=>el.addEventListener('input',()=>{state.storyboard[Number(el.dataset.storyPrompt)].prompt=el.value;save()}))}
  renderStoryboard();

  $$('[data-check]').forEach(el=>{const k=el.dataset.check;el.checked=!!state.checks[k];el.addEventListener('change',()=>{state.checks[k]=el.checked;save();updateEthics()})});
  function updateEthics(){const ok=['consent','harm','label','education'].every(k=>state.checks[k]);const s=$('#ethicsStatus'),lab=$('#simulationLab');s.classList.toggle('locked',!ok);s.classList.toggle('open',ok);s.textContent=ok?'✅ Feu vert : mission autorisée':'🔒 Mission verrouillée';lab.classList.toggle('locked-area',!ok);$$('input,textarea',lab).forEach(el=>el.disabled=!ok)} updateEthics();

  $$('.school-tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.school-tabs button').forEach(b=>b.classList.toggle('active',b===btn));$$('.school-lab').forEach(p=>p.classList.toggle('active',p.dataset.schoolPanel===btn.dataset.schoolTab));if(btn.dataset.schoolTab==='hggsp'){timerSeconds=600}else timerSeconds=900;pauseTimer();updateTimer()}));
  const oralQuestions=[
    "Expliquez en 30 secondes l'idée principale de votre deuxième partie.",
    "Quel exemple de votre réponse est le plus fragile ? Pourquoi ?",
    "Définissez avec vos propres mots un concept utilisé dans le texte.",
    "Quel contre-argument pourrait affaiblir votre réponse ?",
    "Si l'IA a inventé un exemple ou une date, comment le vérifieriez-vous ?",
    "Quelle partie du travail prouve réellement votre compréhension ?",
    "Résumez la réponse obtenue sans reprendre une phrase de l'IA."
  ];
  $('#drawOral').addEventListener('click',()=>{let q;do{q=oralQuestions[Math.floor(Math.random()*oralQuestions.length)]}while(q===state.oral&&oralQuestions.length>1);state.oral=q;$('#oralQuestion').textContent=q;save()}); $('#oralQuestion').textContent=state.oral||'Cliquez pour tirer une question.';

  function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function updateTimer(){if($('#timerDisplay'))$('#timerDisplay').textContent=fmt(timerSeconds);const mins=Math.ceil((durationByStep[activeStep]||600)/60);$('#timerPreset').textContent=`${mins} min`;$('#timerLabel').textContent=['Équipe','Hymne IA','Vidéo promo','Simulation IA','Travail scolaire','Débrief'][activeStep]||'Prêt'}
  function startTimer(){if(timerRunning)return;timerRunning=true;timerId=setInterval(()=>{timerSeconds--;updateTimer();if(timerSeconds===120)toast('⏳','Plus que 2 minutes','Commencez à formuler votre conclusion.');if(timerSeconds===30)toast('⚡','30 secondes','Finalisez votre trace de travail.');if(timerSeconds<=0){pauseTimer();timerSeconds=0;updateTimer();toast('⏱️','Temps écoulé','Passez au débrief avant de continuer.')}},1000)}
  function pauseTimer(){if(timerId)clearInterval(timerId);timerRunning=false} function resetTimer(){pauseTimer();timerSeconds=durationByStep[activeStep]||600;updateTimer()}
  $('#timerStart').addEventListener('click',startTimer);$('#timerPause').addEventListener('click',pauseTimer);$('#timerReset').addEventListener('click',resetTimer);

  function teamHtml(){const valid=state.team.filter(p=>p.name||p.school);return valid.length?valid.map(p=>`<li><strong>${esc(p.name||'—')}</strong> — ${esc(p.school||'—')} <em>${esc(p.role||'')}</em></li>`).join(''):'<li>—</li>'}
  function f(k){return esc(state.fields[k]||'—')}
  function delegation(k){const ai=Number(state.ranges[k]??50);return `${ai}% IA / ${100-ai}% humain`}
  function summaryHtml(){const sb=state.storyboard.map((s,i)=>`<div class="print-story"><strong>Plan ${i+1}</strong><div>${esc(s.scene||'—')}</div><small>Prompt : ${esc(s.prompt||'—')}</small></div>`).join('');return `<div class="preview-doc ia-preview"><div class="preview-logos"><img src="assets/logo-zese.png"><img src="assets/logo-aefe.png"></div><h1>LAB IA — L'IA peut tout faire… ou presque</h1><p><strong>${esc(state.groupName||'Groupe non renseigné')}</strong></p><section><h2>Notre équipe</h2><ul>${teamHtml()}</ul></section>
  <section><h2>🎵 Mission 1 — Hymne</h2><h3>Outil</h3><div class="answer">${f('m1_tool')}</div><h3>Prompt exact</h3><div class="answer">${f('m1_prompt')}</div><h3>Production</h3><div class="answer">${f('m1_output')}</div><h3>Modifications humaines</h3><div class="answer">${f('m1_human_changes')}</div><h3>Délégation</h3><div class="answer">${delegation('m1_ai')}</div><h3>Débrief</h3><div class="answer">Temps : ${f('m1_time')}<br>Notre part : ${f('m1_ours')}<br>Auteur : ${f('m1_author')}<br>Sans IA : ${f('m1_without')}</div><h3>Réflexion</h3><div class="answer">${f('m1_reflection')}</div></section>
  <section><h2>🎬 Mission 2 — Vidéo promotionnelle</h2><div class="print-story-grid">${sb}</div><h3>Slogan</h3><div class="answer">${f('m2_slogan')}</div><h3>Voix off</h3><div class="answer">${f('m2_voice')}</div><h3>Outils / prompts</h3><div class="answer">${f('m2_tools')}<br>${f('m2_prompts')}</div><h3>Modifications humaines</h3><div class="answer">${f('m2_human_changes')}</div><h3>Délégation</h3><div class="answer">${delegation('m2_ai')}</div><h3>Réflexion</h3><div class="answer">${f('m2_reflection')}</div></section>
  <section><h2>🎭 Mission 3 — Simulation IA</h2><div class="answer">Personnage : ${f('m3_person')}<br>Message : ${f('m3_message')}<br>Prompt : ${f('m3_prompt')}<br>Outil : ${f('m3_tool')}</div><h3>Manipulation / vérification / responsabilité</h3><div class="answer">${f('m3_manipulation')}<br><br>${f('m3_verify')}<br><br>${f('m3_responsibility')}</div><h3>Délégation</h3><div class="answer">${delegation('m3_ai')}</div><h3>Réflexion</h3><div class="answer">${f('m3_reflection')}</div></section>
  <section><h2>📚 Expérimentation scolaire</h2><h3>Philosophie</h3><div class="answer">Sujet : ${f('p_subject')}<br>Prompt : ${f('p_prompt')}<br>Résultat : ${f('p_result')}<br>Temps IA : ${f('p_ai_time')} / sans IA : ${f('p_normal_time')}<br>Erreurs : ${f('p_errors')}<br>Corrections : ${f('p_changes')}<br>Ce que nous ne saurions pas expliquer : ${f('p_unknown')}</div><h3>HGGSP</h3><div class="answer">Sujet : ${f('h_subject')}<br>Prompt : ${f('h_prompt')}<br>Résultat : ${f('h_result')}<br>À vérifier : ${f('h_verify')}<br>Corrections : ${f('h_changes')}<br>Compétences non prouvées : ${f('h_unknown')}</div><h3>Oral surprise</h3><div class="answer">Question : ${esc(state.oral||'—')}<br>Réponse : ${f('oral_answer')}</div></section>
  <section><h2>🧭 Débrief final</h2><div class="answer">Produire vite = comprendre ? ${state.ranges.d_speed??3}/5 — ${f('d_speed_reason')}<br><br>Évaluation scolaire : ${state.ranges.d_eval??3}/5 — ${f('d_eval_reason')}<br><br>Interdire / intégrer : ${state.ranges.d_integrate??3}/5 — ${f('d_integrate_reason')}</div><h3>3 forces</h3><ol><li>${f('force1')}</li><li>${f('force2')}</li><li>${f('force3')}</li></ol><h3>3 risques</h3><ol><li>${f('risk1')}</li><li>${f('risk2')}</li><li>${f('risk3')}</li></ol><h3>Question éthique</h3><div class="answer">${f('ethical_question')}</div><h3>Compétence humaine irremplaçable</h3><div class="answer">${f('human_skill')}</div><div class="manifesto-quote">${f('final_rule')}</div></section></div>`}

  $('#previewBtn').addEventListener('click',()=>{$('#previewContent').innerHTML=summaryHtml();$('#previewDialog').showModal()});$('#closePreview').addEventListener('click',()=>$('#previewDialog').close());
  function printSummary(){const old=$('#printSummary');if(old)old.remove();const el=document.createElement('div');el.id='printSummary';el.className='print-summary';el.innerHTML=summaryHtml();document.body.appendChild(el);document.body.classList.add('printing-summary');const cleanup=()=>{document.body.classList.remove('printing-summary');el.remove();window.removeEventListener('afterprint',cleanup)};window.addEventListener('afterprint',cleanup);setTimeout(()=>window.print(),100)}
  $('#pdfBtn').addEventListener('click',async()=>{const filename=`LAB_IA_${(state.groupName||'groupe').replace(/[^a-z0-9_-]+/gi,'_')}.pdf`;const result=await window.IntercvlDriveSync?.generateAndSendPdf({atelier:'atelier-ia',tableName:state.groupName,jsonBackup:state,html:summaryHtml(),statusEl:$('#driveSyncStatus'),filename});if(result?.ok)toast('✅','PDF enregistré','Le PDF a été généré et enregistré directement dans le Drive de l’équipe organisatrice.');});
  $('#backupBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`LAB_IA_${(state.groupName||'groupe').replace(/[^a-z0-9_-]+/gi,'_')}.json`;a.click();URL.revokeObjectURL(a.href)});
  $('#restoreInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state={...emptyState(),...JSON.parse(r.result)};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));location.reload()}catch{alert('Sauvegarde invalide.')}};r.readAsText(file)});
  $('#resetAll').addEventListener('click',()=>{if(confirm('Effacer toutes les données de cet atelier sur cet appareil ?')){localStorage.removeItem(STORAGE_KEY);location.reload()}});
  $('#driveSyncBtn')?.addEventListener('click',()=>{window.IntercvlDriveSync?.send('atelier-ia',state.groupName,state,$('#driveSyncStatus'))});

  updateEthics();updateTimer();go(activeStep);
})();
