(() => {
  const STORAGE_KEY='intercvl-zese-atelier3-v1';
  const A1_KEY='intercvl-zese-atelier1-v1', A2_KEY='intercvl-zese-atelier2-v1';
  const emptyState=()=>({tableName:'',currentStep:0,participants:[],fields:{},ideas:[],values:[],planRows:[],importedSources:[],canvas:null});
  let state=loadState();
  state.participants ||= []; state.fields ||= {}; state.ideas ||= []; state.values ||= []; state.planRows ||= []; state.importedSources ||= [];
  let activeStep=Number(state.currentStep||0), timerSeconds=1200, timerId=null, timerRunning=false, drawing=false, erase=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function loadState(){try{return {...emptyState(),...(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}}catch{return emptyState()}}
  function saveState(show=true){state.currentStep=activeStep;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show){const el=$('#saveStatus');if(el){el.textContent='✓ Sauvegardé sur cet appareil';setTimeout(()=>el.textContent='💾 Sauvegarde locale active',1100)}}}
  function go(step){activeStep=Number(step);$$('.panel').forEach(p=>p.classList.toggle('visible',Number(p.dataset.panel)===activeStep));$$('.step').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===activeStep));saveState(false);renderFoundation();renderContributors();window.scrollTo({top:0,behavior:'smooth'})}
  $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$$('.step').forEach(b=>b.addEventListener('click',()=>go(b.dataset.step)));

  $('#tableName').value=state.tableName||'';$('#tableName').addEventListener('input',e=>{state.tableName=e.target.value;saveState()});
  $$('[data-field]').forEach(el=>{const k=el.dataset.field;el.value=state.fields[k]??'';el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{state.fields[k]=el.value;saveState(false)})});

  // Participants
  const pd=$('#participantDialog3'), pf=$('#participantForm3');
  function renderContributors(){const box=$('#peopleSidebar');if(box)box.innerHTML=state.participants.length?state.participants.map((p,i)=>`<span class="person-chip"><strong>${esc(p.name)}</strong><small>${esc(p.school)}</small><button data-remove-person="${i}" title="Supprimer">×</button></span>`).join(''):'<span class="empty-note">Aucun prénom ajouté.</span>';$$('[data-remove-person]').forEach(b=>b.addEventListener('click',()=>{state.participants.splice(Number(b.dataset.removePerson),1);saveState();renderContributors()}));const all=$('#allContributors3');if(all){const g={};state.participants.forEach(p=>(g[p.school]||=[]).push(p.name));all.innerHTML=Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0])).map(([s,n])=>`<div class="school-group"><strong>${esc(s)}</strong> — ${[...new Set(n)].map(esc).join(', ')}</div>`).join('')||'<span class="empty-note">Aucun nom renseigné.</span>'}}
  $('#addParticipant').addEventListener('click',()=>{ $('#participantName3').value='';$('#participantSchool3').value='';pd.showModal();setTimeout(()=>$('#participantName3').focus(),50)});
  pf.addEventListener('submit',e=>{e.preventDefault();const name=$('#participantName3').value.trim(),school=$('#participantSchool3').value.trim();if(!name||!school)return;const dup=state.participants.some(p=>p.name.toLowerCase()===name.toLowerCase()&&p.school.toLowerCase()===school.toLowerCase());if(!dup)state.participants.push({name,school});saveState();renderContributors();pd.close()});

  // Timer 20 min
  function timerText(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function updateTimer(){$('#timerDisplay').textContent=timerText(timerSeconds)}
  function toast(icon,title,text,long=false){const t=$('#rotationToast3');t.querySelector('.toast-icon').textContent=icon;t.querySelector('strong').textContent=title;t.querySelector('span').textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),long?6000:3500)}
  function startTimer(){if(timerRunning)return;timerRunning=true;timerId=setInterval(()=>{timerSeconds--;updateTimer();if(timerSeconds===300)toast('⏳','5 minutes restantes','Commencez à sélectionner les idées que vous voulez vraiment garder.');if(timerSeconds===120)toast('⭐','2 minutes restantes','Décidez ce que vous gardez comme vision commune.');if(timerSeconds<=0){clearInterval(timerId);timerRunning=false;timerSeconds=0;updateTimer();toast('✅','Stabilisation terminée','Passez de la banque d’idées au dispositif structuré.',true)}},1000)}
  $('#timerStart').addEventListener('click',startTimer);$('#timerPause').addEventListener('click',()=>{clearInterval(timerId);timerRunning=false});$('#timerReset').addEventListener('click',()=>{clearInterval(timerId);timerRunning=false;timerSeconds=1200;updateTimer()});

  // Idea import helpers
  const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLowerCase();
  function addIdea(text,source){text=String(text||'').trim();if(text.length<3)return false;if(state.ideas.some(i=>norm(i.text)===norm(text)))return false;state.ideas.push({id:crypto?.randomUUID?.()||`${Date.now()}_${Math.random()}`,text,source:source||'Ajout manuel',recurring:false,clear:false,actionable:false,core:false});return true}
  function addFieldIdea(data,key,label,source){const v=data?.fields?.[key];if(v&&String(v).trim())addIdea(`${label} : ${String(v).trim()}`,source)}
  function extractA1(data,source='Atelier 1'){
    ['final_device','final_operation','final_next','r3_idea','r3_tool','r3_first','r4_frequency','r4_handover','r4_reflection','r2_priority'].forEach(k=>{
      const labels={final_device:'Dispositif proposé',final_operation:'Fonctionnement imaginé',final_next:'Première action',r3_idea:'Idée de réseau',r3_tool:'Outil / format',r3_first:'Premier geste',r4_frequency:'Fréquence',r4_handover:'Passage de relais',r4_reflection:'Durabilité',r2_priority:'Frein prioritaire'};addFieldIdea(data,k,labels[k],source)});
  }
  function extractA2(data,source='Atelier 2'){
    ['final_name','final_action','final_people','final_why','final_comms','final_welcome','final_transmit','r2_combo','r4_reflection'].forEach(k=>{const labels={final_name:'Nom d’action',final_action:'Action emblématique',final_people:'Qui participe / rôles',final_why:'Motivation',final_comms:'Communication',final_welcome:'Accueil des nouveaux',final_transmit:'Transmission',r2_combo:'Système de communication',r4_reflection:'Durabilité'};addFieldIdea(data,k,labels[k],source)});
    const c=data?.selectedConcept;if(c){const l=String(c).toLowerCase(),name=data?.fields?.[`r3_${l}_name`],pitch=data?.fields?.[`r3_${l}_pitch`];if(name||pitch)addIdea(`Action retenue : ${[name,pitch].filter(Boolean).join(' — ')}`,source)}
    const m=data?.selectedManifesto;if(m){const txt=data?.fields?.[`manifesto_${m}`];if(txt)addIdea(`Manifeste : Ce réseau vit parce que ${String(txt).replace(/^ce réseau vit parce que\s*/i,'')}`,source)}
    ['engagement','belonging','visibility'].forEach(t=>(data?.ideas?.[t]||[]).filter(i=>i.voted).forEach(i=>addIdea(`Idée votée : ${i.text}`,source)));
  }
  function detectAndExtract(data,label){let before=state.ideas.length;if(data?.ideas||data?.selectedConcept||data?.fields?.final_action)extractA2(data,label||'Atelier 2');else if(data?.fields?.final_device||data?.fields?.r3_idea)extractA1(data,label||'Atelier 1');return state.ideas.length-before}
  function markSource(s){if(!state.importedSources.includes(s))state.importedSources.push(s)}
  function renderImportStatus(){const el=$('#importStatus');el.textContent=state.importedSources.length?`Sources récupérées : ${state.importedSources.join(' • ')} — ${state.ideas.length} idée(s) dans la banque.`:'Aucune production importée pour le moment.'}
  $('#importLocal').addEventListener('click',()=>{let count=0;try{const a=JSON.parse(localStorage.getItem(A1_KEY)||'null');if(a){const c=state.ideas.length;extractA1(a,'Atelier 1 — cet appareil');count+=state.ideas.length-c;markSource('Atelier 1 local')}}catch{}try{const a=JSON.parse(localStorage.getItem(A2_KEY)||'null');if(a){const c=state.ideas.length;extractA2(a,'Atelier 2 — cet appareil');count+=state.ideas.length-c;markSource('Atelier 2 local')}}catch{}saveState();renderIdeas();renderImportStatus();toast(count?'↙':'ℹ️',count?'Productions récupérées':'Rien à récupérer',count?`${count} nouvelle(s) idée(s) ajoutée(s).`:'Importez les fichiers de sauvegarde si les ateliers ont été réalisés sur un autre appareil.')});
  $('#importBackups').addEventListener('change',e=>{const files=[...e.target.files];if(!files.length)return;let remaining=files.length,total=0;files.forEach(file=>{const fr=new FileReader();fr.onload=()=>{try{const data=JSON.parse(fr.result);const c=detectAndExtract(data,file.name);total+=c;if(c)markSource(file.name)}catch{}finally{remaining--;if(!remaining){saveState();renderIdeas();renderImportStatus();toast('📂','Import terminé',`${total} nouvelle(s) idée(s) ajoutée(s) depuis ${files.length} fichier(s).`,true);e.target.value=''}}};fr.readAsText(file)})});
  $('#addManualIdea').addEventListener('click',()=>{const inp=$('#manualIdea');if(addIdea(inp.value,'Ajout du groupe')){inp.value='';saveState();renderIdeas()}else toast('ℹ️','Idée non ajoutée','Elle est vide ou déjà présente dans la banque.')});
  $('#manualIdea').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#addManualIdea').click()}});

  function renderIdeas(){const box=$('#ideaBank');if(!state.ideas.length){box.innerHTML='<div class="empty-idea-bank"><strong>Votre banque est vide.</strong><span>Récupérez les ateliers 1 et 2 ou ajoutez une idée manuellement.</span></div>';renderFoundation();return}box.innerHTML=state.ideas.map((i,idx)=>`<article class="stabilize-idea ${i.core?'core':''}"><div class="idea-meta"><span>${esc(i.source)}</span><strong>${[i.recurring,i.clear,i.actionable].filter(Boolean).length}/3</strong></div><p>${esc(i.text)}</p><div class="idea-criteria"><button data-idea-toggle="recurring" data-i="${idx}" class="${i.recurring?'active':''}">🔁 Revient souvent</button><button data-idea-toggle="clear" data-i="${idx}" class="${i.clear?'active':''}">💬 Claire</button><button data-idea-toggle="actionable" data-i="${idx}" class="${i.actionable?'active':''}">🚀 Réalisable</button><button data-idea-toggle="core" data-i="${idx}" class="core-btn ${i.core?'active':''}">⭐ À garder</button><button data-idea-delete data-i="${idx}" class="idea-trash" title="Supprimer">×</button></div></article>`).join('');$$('[data-idea-toggle]').forEach(b=>b.addEventListener('click',()=>{const i=state.ideas[Number(b.dataset.i)],k=b.dataset.ideaToggle;i[k]=!i[k];saveState();renderIdeas()}));$$('[data-idea-delete]').forEach(b=>b.addEventListener('click',()=>{state.ideas.splice(Number(b.dataset.i),1);saveState();renderIdeas()}));renderFoundation()}
  function renderFoundation(){const box=$('#foundationIdeas');if(!box)return;const core=state.ideas.filter(i=>i.core);box.innerHTML=core.length?`<div class="foundation-head"><span class="kicker">Les idées retenues comme base du réseau</span><strong>${core.length}</strong></div><div class="foundation-list">${core.map(i=>`<span>⭐ ${esc(i.text)}</span>`).join('')}</div>`:`<div class="foundation-empty">⭐ Aucune idée n'a encore été marquée « À garder ». Revenez à l'étape précédente et choisissez quelques idées qui serviront de base au réseau.</div>`}

  // values
  function renderValues(){$$('#valueChips button').forEach(b=>b.classList.toggle('active',state.values.includes(b.dataset.value)))}
  $$('#valueChips button').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.value;if(state.values.includes(v))state.values=state.values.filter(x=>x!==v);else if(state.values.length<4)state.values.push(v);else return toast('⚠️','4 valeurs maximum','Retirez une valeur avant d’en choisir une autre.');saveState();renderValues()}));

  // Plan table
  function renderPlan(){const body=$('#planRows');if(!body)return;body.innerHTML=state.planRows.length?state.planRows.map((r,i)=>`<tr><td><input data-plan="step" data-pi="${i}" value="${esc(r.step||'')}" placeholder="Étape"></td><td><input data-plan="owner" data-pi="${i}" value="${esc(r.owner||'')}" placeholder="Responsable"></td><td><input data-plan="date" data-pi="${i}" value="${esc(r.date||'')}" placeholder="Échéance"></td><td><input data-plan="metric" data-pi="${i}" value="${esc(r.metric||'')}" placeholder="Comment vérifier ?"></td><td><button class="plan-delete" data-plan-delete="${i}" title="Supprimer">×</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty-note">Aucune étape. Ajoutez une ligne ou préremplissez le plan.</td></tr>';$$('[data-plan]').forEach(inp=>inp.addEventListener('input',()=>{state.planRows[Number(inp.dataset.pi)][inp.dataset.plan]=inp.value;saveState(false)}));$$('[data-plan-delete]').forEach(b=>b.addEventListener('click',()=>{state.planRows.splice(Number(b.dataset.planDelete),1);saveState();renderPlan()}))}
  $('#addPlanRow').addEventListener('click',()=>{state.planRows.push({step:'',owner:'',date:'',metric:''});saveState();renderPlan()});
  $('#prefillPlan').addEventListener('click',()=>{const rows=[];if((state.fields.action_first||'').trim())rows.push({step:state.fields.action_first,owner:state.fields.action_pilots||'',date:'',metric:state.fields.action_metrics||''});if((state.fields.action_next||'').trim())rows.push({step:state.fields.action_next,owner:'',date:'',metric:state.fields.action_metrics||''});if(!rows.length)return toast('ℹ️','Rien à préremplir','Renseignez d’abord la première action et les actions suivantes.');state.planRows=rows;saveState();renderPlan();toast('🗓️','Plan prérempli','Vous pouvez maintenant préciser qui fait quoi, pour quand, et comment vérifier que c’est fait.')});

  // Canvas
  const canvas=$('#networkCanvas3'),ctx=canvas.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4;ctx.strokeStyle='#1010a0';
  function restoreCanvas(){if(!state.canvas)return;const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=state.canvas}
  function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}
  canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=pos(e);ctx.globalCompositeOperation=erase?'destination-out':'source-over';ctx.lineWidth=erase?28:4;ctx.strokeStyle='#1010a0';ctx.lineTo(p.x,p.y);ctx.stroke()});function stop(){if(!drawing)return;drawing=false;ctx.globalCompositeOperation='source-over';state.canvas=canvas.toDataURL('image/png');saveState(false)}canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);
  $('#penBtn3').addEventListener('click',()=>{erase=false;$('#penBtn3').classList.add('active');$('#eraserBtn3').classList.remove('active')});$('#eraserBtn3').addEventListener('click',()=>{erase=true;$('#eraserBtn3').classList.add('active');$('#penBtn3').classList.remove('active')});$('#clearCanvas3').addEventListener('click',()=>{if(confirm('Effacer tout le schéma ?')){ctx.clearRect(0,0,canvas.width,canvas.height);state.canvas=null;saveState()}});restoreCanvas();

  // Pitch
  function generatePitch(){const f=state.fields,name=(f.device_name||'notre réseau').trim(),obj=(f.device_objective||'').trim(),first=(f.action_first||'').trim(),join=(f.device_join||'').trim(),msg=(f.network_message||'').trim();const values=state.values.join(', ');const parts=[`Nous sommes partis d'un constat simple : ${obj||'nous avons besoin d’un réseau inter-établissements utile, vivant et durable.'}`,`Notre proposition s'appelle « ${name} ». ${f.device_coherence||''}`.trim(),`Concrètement, le réseau fonctionne ainsi : ${join||f.device_frequency||'les établissements peuvent le rejoindre facilement et participer à un rythme régulier.'}`,`Notre première action sera : ${first||'lancer une première expérimentation rapidement avec des établissements pilotes.'}`,`Nos valeurs sont ${values||'la coopération et l’ouverture'}. ${msg?`Notre message fondateur : « Ce réseau existe pour ${msg.replace(/^ce réseau existe pour\s*/i,'')} ».`:''}`,`Nous invitons maintenant les établissements volontaires à rejoindre le dispositif, à l'expérimenter et à contribuer à son amélioration.`];state.fields.final_pitch=parts.join('\n\n');$('#pitchText').value=state.fields.final_pitch;saveState();toast('✨','Trame générée','Relisez-la, simplifiez-la et appropriez-vous-la avant la restitution.')}
  $('#generatePitch').addEventListener('click',generatePitch);

  const labelMap={stabilize_recurrences:'Récurrences et consensus',stabilize_core:'Base du réseau retenue',device_name:'Nom du dispositif',device_objective:'Objectif en 1 phrase',device_initiator:'Qui initie ?',device_join:'Comment rejoindre ?',device_frequency:'Fréquence',device_sustain:'Comment durer ?',device_coherence:'Pourquoi le projet est utile, réaliste et capable de rassembler ?',network_message:'Ce réseau existe pour…',action_first:'Première action à lancer',action_next:'Actions suivantes',action_pilots:'Établissements pilotes',action_metrics:'Comment vérifier que ça marche ?',action_students:'Votre engagement',final_pitch:'Pitch 2–3 minutes'};
  function answer(k){return `<h3>${esc(labelMap[k]||k)}</h3><div class="answer">${esc(state.fields[k]||'—')}</div>`}
  function planHtml(){return state.planRows.length?`<table class="print-plan"><thead><tr><th>Étape</th><th>Responsable</th><th>Échéance</th><th>Comment vérifier ?</th></tr></thead><tbody>${state.planRows.map(r=>`<tr><td>${esc(r.step||'—')}</td><td>${esc(r.owner||'—')}</td><td>${esc(r.date||'—')}</td><td>${esc(r.metric||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="answer">Aucune ligne de plan d’action renseignée.</div>'}
  function contributorsHtml(){const g={};state.participants.forEach(p=>(g[p.school]||=[]).push(p.name));return Object.entries(g).map(([s,n])=>`<div><strong>${esc(s)}</strong> — ${[...new Set(n)].map(esc).join(', ')}</div>`).join('')||'—'}
  function summaryHtml(){const core=state.ideas.filter(i=>i.core);const canvasImg=state.canvas?`<img src="${state.canvas}" style="width:100%;border:1px solid #ddd;border-radius:8px">`:'<div class="answer">Aucun schéma réalisé.</div>';return `<div class="preview-doc"><div class="preview-logos"><img src="assets/logo-zese.png"><img src="assets/logo-aefe.png"></div><div class="workshop-cover"><span class="pdf-eyebrow">INTER-CVL ZESE • NICOSIE • CARNET DE TRACES</span><h1>Atelier 3</h1><h2>Construire le Réseau</h2><p class="pdf-table-name">${esc(state.tableName||'Groupe non renseigné')}</p></div>
  <section><h2>1. Stabilisation des idées</h2><h3>Idées retenues comme base du réseau</h3><ul>${core.length?core.map(i=>`<li>${esc(i.text)} <em>— ${esc(i.source)}</em></li>`).join(''):'<li>—</li>'}</ul>${answer('stabilize_recurrences')}${answer('stabilize_core')}</section>
  <section><h2>2. Dispositif structuré</h2>${answer('device_name')}${answer('device_objective')}${answer('device_initiator')}${answer('device_join')}${answer('device_frequency')}${answer('device_sustain')}${answer('device_coherence')}<h3>Schéma global du réseau</h3>${canvasImg}</section>
  <section><h2>3. Identité du réseau</h2><h3>Valeurs communes</h3><div class="answer">${esc(state.values.join(' • ')||'—')}</div>${answer('network_message')}</section>
  <section><h2>4. Projection et engagement</h2>${answer('action_first')}${answer('action_next')}${answer('action_pilots')}${answer('action_metrics')}${answer('action_students')}<h3>Mini plan d'action</h3>${planHtml()}</section>
  <section><h2>5. Pitch de présentation</h2>${answer('final_pitch')}</section>
  <section><h2>Votre équipe</h2>${contributorsHtml()}</section></div>`}
  $('#previewBtn3').addEventListener('click',()=>{$('#previewContent3').innerHTML=summaryHtml();$('#previewDialog3').showModal()});$('#closePreview3').addEventListener('click',()=>$('#previewDialog3').close());
  function printSummary(){const old=$('#printSummary');if(old)old.remove();const div=document.createElement('div');div.id='printSummary';div.className='print-summary';div.innerHTML=summaryHtml();document.body.appendChild(div);document.body.classList.add('printing-summary');const cleanup=()=>{document.body.classList.remove('printing-summary');div.remove();window.removeEventListener('afterprint',cleanup)};window.addEventListener('afterprint',cleanup);setTimeout(()=>window.print(),80)}
  $('#pdfBtn3').addEventListener('click',async()=>{const filename=`Atelier3_ConstruireReseau_${(state.tableName||'groupe').replace(/[^a-z0-9_-]+/gi,'_')}.pdf`;const result=await window.IntercvlDriveSync?.generateAndSendPdf({atelier:'atelier3',tableName:state.tableName,jsonBackup:state,html:summaryHtml(),statusEl:$('#driveSyncStatus3'),filename});if(result?.ok)toast('✅','PDF enregistré','Le PDF a été généré et enregistré directement dans le Drive de l’équipe organisatrice.',true)});
  $('#backupBtn3').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Atelier3_${(state.tableName||'groupe').replace(/[^a-z0-9_-]+/gi,'_')}_sauvegarde.json`;a.click();URL.revokeObjectURL(a.href)});
  $('#restoreInput3').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const fr=new FileReader();fr.onload=()=>{try{state={...emptyState(),...JSON.parse(fr.result)};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));location.reload()}catch{alert("Ce fichier de sauvegarde n'est pas valide.")}};fr.readAsText(f)});
  $('#driveSyncBtn3')?.addEventListener('click',()=>{window.IntercvlDriveSync?.send('atelier3',state.tableName,state,$('#driveSyncStatus3'))});
  $('#resetAll3').addEventListener('click',()=>{if(confirm('Effacer toutes les notes, les idées, les prénoms et le schéma de ce groupe ?')){localStorage.removeItem(STORAGE_KEY);location.reload()}});

  renderContributors();renderIdeas();renderImportStatus();renderValues();renderPlan();updateTimer();go(activeStep);
})();
