(() => {
  const STORAGE_KEY='intercvl-zese-atelier2-v1';
  const emptyState=()=>({
    tableName:'',currentStep:0,
    participants:{1:[],2:[],3:[],4:[]},initializedRotations:{1:true,2:false,3:false,4:false},
    fields:{},selected:{},chips:{discuss:[],react:[],cocreate:[]},
    ideas:{engagement:[],belonging:[],visibility:[]},
    ranges:{},selectedConcept:'',creativeChallenge:'',selectedManifesto:''
  });
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function loadState(){try{return {...emptyState(),...(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}}catch{return emptyState()}}
  let state=loadState();
  state.participants ||= {1:[],2:[],3:[],4:[]}; state.initializedRotations ||= {1:true,2:false,3:false,4:false};
  state.fields ||= {}; state.selected ||= {}; state.chips ||= {discuss:[],react:[],cocreate:[]}; state.ideas ||= {engagement:[],belonging:[],visibility:[]}; state.ranges ||= {};
  [1,2,3,4].forEach(r=>{state.participants[r]||=[];if(r===1||state.participants[r].length)state.initializedRotations[r]=true});
  ['engagement','belonging','visibility'].forEach(k=>state.ideas[k]||=[]);
  ['discuss','react','cocreate'].forEach(k=>state.chips[k]||=[]);
  let activeStep=Number(state.currentStep||0), timerSeconds=600,timerId=null,timerRunning=false,currentParticipantRotation=1;
  function saveState(show=true){state.currentStep=activeStep;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show){const el=$('#saveStatus');if(el){el.textContent='✓ Sauvegardé sur cet appareil';setTimeout(()=>el.textContent='💾 Sauvegarde locale active',1200)}}}

  function ensureRotationParticipants(r){r=Number(r);if(r<2||r>4)return;if(!state.initializedRotations[r]){state.participants[r]=(state.participants[r-1]||[]).map(p=>({...p}));state.initializedRotations[r]=true;saveState(false)}}
  function go(step){activeStep=Number(step);if(activeStep>=2&&activeStep<=4)ensureRotationParticipants(activeStep);if(activeStep===5)prefillFinal();$$('.panel').forEach(p=>p.classList.toggle('visible',Number(p.dataset.panel)===activeStep));$$('.step').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===activeStep));saveState(false);resetTimer();updateRelayPreviews();if(activeStep>=1&&activeStep<=4)renderContributors(activeStep);renderAllContributors();renderManifesto();window.scrollTo({top:0,behavior:'smooth'})}
  $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$$('.step').forEach(b=>b.addEventListener('click',()=>go(b.dataset.step)));

  $('#tableName').value=state.tableName||'';$('#tableName').addEventListener('input',e=>{state.tableName=e.target.value;saveState()});
  $$('[data-field]').forEach(el=>{const k=el.dataset.field;el.value=state.fields[k]??'';el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{state.fields[k]=el.value;saveState();updateRelayPreviews();renderManifesto()})});
  $$('[data-segment]').forEach(group=>{const k=group.dataset.segment;$$('button',group).forEach(btn=>{btn.classList.toggle('active',state.selected[k]===btn.dataset.value);btn.addEventListener('click',()=>{state.selected[k]=btn.dataset.value;$$('button',group).forEach(b=>b.classList.toggle('active',b===btn));saveState()})})});

  const dialog=$('#participantDialog'),form=$('#participantForm');
  function renderContributors(rotation){const box=$(`.contributors[data-rotation="${rotation}"]`);if(!box)return;const list=state.participants[rotation]||[];const carry=rotation>1?`<div class="carry-note">↪️ Les prénoms de la rotation ${rotation-1} ont été repris. Retirez le prénom de la personne partie comme ambassadeur et ajoutez celui de la personne arrivée.</div>`:'';box.innerHTML=`<div class="contributors-head"><div><h3>👥 Qui est autour de la table ?</h3><p class="contributors-sub">Ces prénoms restent enregistrés pour cette rotation.</p></div><button class="btn secondary small add-person" data-r="${rotation}">+ Ajouter un prénom</button></div>${carry}<div class="people-list">${list.length?list.map((p,i)=>`<span class="person-chip"><strong>${esc(p.name)}</strong><small>${esc(p.school)}</small><button title="Supprimer" data-remove="${i}" data-r="${rotation}">×</button></span>`).join(''):'<span class="empty-note">Aucun prénom ajouté.</span>'}</div>`;$('.add-person',box).addEventListener('click',()=>openParticipant(rotation));$$('[data-remove]',box).forEach(btn=>btn.addEventListener('click',()=>{const r=Number(btn.dataset.r),i=Number(btn.dataset.remove);state.participants[r].splice(i,1);saveState();renderContributors(r);renderAllContributors()}))}
  function openParticipant(rotation){currentParticipantRotation=Number(rotation);$('#participantRotation').value=rotation;$('#participantName').value='';$('#participantSchool').value='';const cur=state.participants[currentParticipantRotation]||[];$('#existingPeopleHint').innerHTML=cur.length?`<strong>Déjà enregistrés :</strong><div class="existing-chips">${cur.map(p=>`<span>${esc(p.name)} <small>(${esc(p.school)})</small></span>`).join('')}</div>`:'<span class="empty-note">Aucun nom enregistré.</span>';dialog.showModal();setTimeout(()=>$('#participantName').focus(),60)}
  form.addEventListener('submit',e=>{e.preventDefault();const name=$('#participantName').value.trim(),school=$('#participantSchool').value.trim();if(!name||!school)return;state.participants[currentParticipantRotation]||=[];if(!state.participants[currentParticipantRotation].some(p=>p.name.toLowerCase()===name.toLowerCase()&&p.school.toLowerCase()===school.toLowerCase()))state.participants[currentParticipantRotation].push({name,school});state.initializedRotations[currentParticipantRotation]=true;saveState();renderContributors(currentParticipantRotation);renderAllContributors();dialog.close()});
  [1,2,3,4].forEach(renderContributors);
  function allPeople(){const m=new Map();Object.values(state.participants).flat().forEach(p=>m.set(`${p.name.toLowerCase()}|${p.school.toLowerCase()}`,p));return [...m.values()]}
  function renderAllContributors(){const el=$('#allContributors');if(!el)return;const people=allPeople();if(!people.length){el.innerHTML='<span class="empty-note">Aucun prénom ajouté.</span>';return}const g={};people.forEach(p=>(g[p.school]||=[]).push(p.name));el.innerHTML=Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0])).map(([s,n])=>`<div class="school-group"><strong>${esc(s)}</strong> — ${[...new Set(n)].map(esc).join(', ')}</div>`).join('')}

  function votesUsed(){return Object.values(state.ideas).flat().reduce((n,i)=>n+(i.voted?1:0),0)}
  function renderIdeas(){['engagement','belonging','visibility'].forEach(theme=>{const box=$(`#ideas-${theme}`);if(!box)return;box.innerHTML=state.ideas[theme].length?state.ideas[theme].map((it,i)=>`<div class="idea-note ${it.voted?'voted':''}"><p>${esc(it.text)}</p><div><button class="idea-vote" data-vote-theme="${theme}" data-vote-index="${i}" title="Voter">${it.voted?'⭐':'☆'}</button><button class="idea-delete" data-del-theme="${theme}" data-del-index="${i}" title="Supprimer">×</button></div></div>`).join(''):'<span class="empty-note">Ajoutez vos premières idées.</span>'});const left=Math.max(0,3-votesUsed());$('#votesCounter').textContent=left?`${'⭐'.repeat(left)} disponible${left>1?'s':''}`:'3 étoiles utilisées';$$('[data-vote-theme]').forEach(b=>b.addEventListener('click',()=>{const it=state.ideas[b.dataset.voteTheme][Number(b.dataset.voteIndex)];if(it.voted){it.voted=false}else if(votesUsed()<3){it.voted=true}else{toast('⭐','3 votes utilisés','Retirez une étoile avant d’en attribuer une autre.')}saveState();renderIdeas()}));$$('[data-del-theme]').forEach(b=>b.addEventListener('click',()=>{state.ideas[b.dataset.delTheme].splice(Number(b.dataset.delIndex),1);saveState();renderIdeas()}))}
  $$('[data-add-idea]').forEach(btn=>btn.addEventListener('click',()=>{const theme=btn.dataset.addIdea,input=$(`#ideaInput-${theme}`),text=input.value.trim();if(!text)return;state.ideas[theme].push({text,voted:false});input.value='';saveState();renderIdeas()}));['engagement','belonging','visibility'].forEach(t=>{$(`#ideaInput-${t}`).addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$(`[data-add-idea="${t}"]`).click()}})});renderIdeas();

  $$('[data-chip-group]').forEach(group=>{const key=group.dataset.chipGroup;$$('button',group).forEach(btn=>{btn.classList.toggle('active',state.chips[key].includes(btn.textContent.trim()));btn.addEventListener('click',()=>{const val=btn.textContent.trim(),arr=state.chips[key];const ix=arr.indexOf(val);if(ix>=0)arr.splice(ix,1);else arr.push(val);btn.classList.toggle('active');saveState()})})});

  $$('[data-range]').forEach(input=>{const k=input.dataset.range;if(state.ranges[k]!=null)input.value=state.ranges[k];$(`[data-range-out="${k}"]`).textContent=input.value;input.addEventListener('input',()=>{state.ranges[k]=Number(input.value);$(`[data-range-out="${k}"]`).textContent=input.value;saveState()})});
  $$('[data-select-concept]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedConcept=btn.dataset.selectConcept;$$('.concept-card').forEach(c=>c.classList.toggle('selected',c.dataset.concept===state.selectedConcept));saveState();toast('🏆','Idée retenue',`L'idée ${state.selectedConcept} devient la base à tester.`)}));$$('.concept-card').forEach(c=>c.classList.toggle('selected',c.dataset.concept===state.selectedConcept));
  const challenges=["Votre projet doit pouvoir commencer avec 0 €.","Un établissement qui rejoint le réseau demain doit pouvoir participer immédiatement.","Votre action doit pouvoir impliquer au moins 5 pays.","Votre action doit produire quelque chose de visible en moins de 24 h.","Interdiction d'utiliser Instagram ou TikTok pour faire connaître le projet.","Une personne timide doit pouvoir y contribuer autant qu'une personne très à l'aise à l'oral.","Votre action doit pouvoir continuer même si aucun des élèves présents aujourd'hui n'est encore là l'année prochaine."];
  function renderChallenge(){$('#challengeText').textContent=state.creativeChallenge||'Tirez une contrainte pour pousser votre idée plus loin.'}
  $('#drawChallenge').addEventListener('click',()=>{let c;do{c=challenges[Math.floor(Math.random()*challenges.length)]}while(c===state.creativeChallenge&&challenges.length>1);state.creativeChallenge=c;saveState();renderChallenge()});renderChallenge();

  function prefillFinal(){if(state.selectedConcept){const l=state.selectedConcept.toLowerCase(),name=state.fields[`r3_${l}_name`]||'',pitch=state.fields[`r3_${l}_pitch`]||'';if(!state.fields.final_name&&name){state.fields.final_name=name;const el=$('[data-field="final_name"]');if(el)el.value=name}if(!state.fields.final_action&&pitch){state.fields.final_action=pitch;const el=$('[data-field="final_action"]');if(el)el.value=pitch}saveState(false)}}
  $$('.select-manifesto').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();state.selectedManifesto=btn.dataset.manifesto;saveState();renderManifesto()}));
  function renderManifesto(){const k=state.selectedManifesto?`manifesto_${state.selectedManifesto}`:'';const txt=k?(state.fields[k]||'').trim():'';$('#manifestoWinner').textContent=txt?`« Ce réseau vit parce que ${txt.replace(/^ce réseau vit parce que\s*/i,'').replace(/^«|»$/g,'')} »`:'Aucune proposition choisie.';$$('.select-manifesto').forEach(b=>b.classList.toggle('active',b.dataset.manifesto===state.selectedManifesto))}

  function updateRelayPreviews(){[['relay1Preview','r1_relay'],['relay2Preview','r2_relay'],['relay3Preview','r3_relay']].forEach(([id,k])=>{const el=$('#'+id);if(el)el.textContent=state.fields[k]?.trim()||'Aucune note pour le moment.'})}

  function timerText(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function updateTimer(){$('#timerDisplay').textContent=timerText(timerSeconds);$('#timerLabel').textContent=activeStep>=1&&activeStep<=4?`Rotation ${activeStep}`:'Prêt'}
  function startTimer(){if(timerRunning||!(activeStep>=1&&activeStep<=4))return;timerRunning=true;timerId=setInterval(()=>{timerSeconds--;updateTimer();if(timerSeconds===120)toast('⏳','Plus que 2 minutes','Préparez votre choix et votre transmission.');if(timerSeconds===30)toast('🗣️','30 secondes','Formulez le message laissé au groupe suivant.');if(timerSeconds<=0){clearInterval(timerId);timerRunning=false;timerSeconds=0;updateTimer();toast('🔄','Rotation !','Accueillez celles et ceux qui arrivent.',true);openParticipant(activeStep)}},1000)}
  function pauseTimer(){if(timerId)clearInterval(timerId);timerRunning=false}function resetTimer(){pauseTimer();timerSeconds=600;updateTimer()}
  $('#timerStart').addEventListener('click',startTimer);$('#timerPause').addEventListener('click',pauseTimer);$('#timerReset').addEventListener('click',resetTimer);
  function toast(icon,title,text,long=false){const t=$('#rotationToast');t.querySelector('.toast-icon').textContent=icon;t.querySelector('strong').textContent=title;t.querySelector('span').textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),long?6000:3500)}

  const labelMap={r1_reflection:'NOTRE RÉFLEXION',r1_relay:'Message transmis',r2_ambassador:"Apport de l'ambassadeur",r2_combo:'Combinaison idéale',r2_inclusion:'Faire entendre tout le monde',r2_reflection:'NOTRE RÉFLEXION',r2_relay:'Message transmis',r3_ambassador:"Apport de l'ambassadeur",r3_challenge_adapt:'Adaptation à la contrainte',r3_reflection:'NOTRE RÉFLEXION',r3_relay:'Message transmis',r4_ambassador:"Apport de l'ambassadeur",r4_newcomer:'Accueillir les nouveaux',r4_energy:"Éviter l'essoufflement",r4_handover:'Transmettre les rôles',r4_memory:'Transmettre la culture',r4_durability_reason:'Condition de durabilité',r4_reflection:'NOTRE RÉFLEXION',r4_relay:'Message final',final_name:"Nom de l'action",final_action:"Action emblématique",final_people:'Qui participe et comment ?',final_why:"Pourquoi cela donne envie ?",final_comms:'Communication',final_welcome:'Accueil des nouveaux',final_transmit:'Transmission'};
  function participantsHtml(r){const l=state.participants[r]||[];return l.length?l.map(p=>`${esc(p.name)} <em>(${esc(p.school)})</em>`).join(' • '):'<em>Aucun nom renseigné</em>'}
  function answers(keys){return keys.map(k=>`<div class="pdf-answer-block"><h3>${esc(labelMap[k]||k)}</h3><div class="answer">${esc(state.fields[k]||'—')}</div></div>`).join('')}
  function ideasHtml(){return ['engagement','belonging','visibility'].map(t=>{const title={engagement:"Envie de participer",belonging:"Sentiment d'appartenance",visibility:'Visibilité'}[t];const l=state.ideas[t]||[];return `<h3>${title}</h3><ul>${l.length?l.map(i=>`<li>${i.voted?'⭐ ':''}${esc(i.text)}</li>`).join(''):'<li>—</li>'}</ul>`}).join('')}
  function conceptHtml(letter){const l=letter.toLowerCase();return `<div class="concept-summary"><h3>${state.selectedConcept===letter?'🏆 ':''}Idée ${letter} — ${esc(state.fields[`r3_${l}_name`]||'Sans nom')}</h3><div class="answer">${esc(state.fields[`r3_${l}_pitch`]||'—')}</div><p>❤️ ${state.ranges[`r3_${l}_emotion`]??3}/5 · 🪪 ${state.ranges[`r3_${l}_identity`]??3}/5 · ⚡ ${state.ranges[`r3_${l}_challenge`]??3}/5</p></div>`}
  function summaryHtml(){const grouped={};allPeople().forEach(p=>(grouped[p.school]||=[]).push(p.name));const all=Object.entries(grouped).map(([s,n])=>`<div><strong>${esc(s)}</strong> — ${[...new Set(n)].map(esc).join(', ')}</div>`).join('')||'—';const manifestKey=state.selectedManifesto?`manifesto_${state.selectedManifesto}`:'';const manifest=manifestKey?state.fields[manifestKey]||'—':'—';return `<div class="preview-doc"><div class="preview-logos"><img src="assets/logo-zese.png"><img src="assets/logo-aefe.png"></div><div class="workshop-cover"><span class="pdf-eyebrow">INTER-CVL ZESE • NICOSIE • CARNET DE TRACES</span><h1>Atelier 2</h1><h2>Vivre Réseau</h2><p class="pdf-table-name">${esc(state.tableName||'Table non renseignée')}</p></div>
  <section><h2>Rotation 1 — Donner envie d'appartenir</h2><p><strong>Prénoms du groupe :</strong> ${participantsHtml(1)}</p>${ideasHtml()}${answers(['r1_reflection','r1_relay'])}</section>
  <section><h2>Rotation 2 — Faire communiquer le réseau</h2><p><strong>Prénoms du groupe :</strong> ${participantsHtml(2)}</p>${answers(['r2_ambassador'])}<h3>Pour discuter</h3><div class="answer">${esc((state.chips.discuss||[]).join(' • ')||'—')}</div><h3>Pour réagir</h3><div class="answer">${esc((state.chips.react||[]).join(' • ')||'—')}</div><h3>Pour co-construire</h3><div class="answer">${esc((state.chips.cocreate||[]).join(' • ')||'—')}</div>${answers(['r2_combo','r2_inclusion','r2_reflection','r2_relay'])}</section>
  <section><h2>Rotation 3 — Action emblématique</h2><p><strong>Prénoms du groupe :</strong> ${participantsHtml(3)}</p>${answers(['r3_ambassador'])}${conceptHtml('A')}${conceptHtml('B')}${conceptHtml('C')}<h3>Contrainte créative</h3><div class="answer">${esc(state.creativeChallenge||'—')}</div>${answers(['r3_challenge_adapt','r3_reflection','r3_relay'])}</section>
  <section><h2>Rotation 4 — Crash-test de durabilité</h2><p><strong>Prénoms du groupe :</strong> ${participantsHtml(4)}</p>${answers(['r4_ambassador','r4_newcomer','r4_energy','r4_handover','r4_memory'])}<h3>Auto-évaluation</h3><div class="answer">${esc(state.selected.r4_durability||'—')}</div>${answers(['r4_durability_reason','r4_reflection','r4_relay'])}</section>
  <section class="manifesto-print"><h2>🌟 Notre action emblématique</h2>${answers(['final_name','final_action','final_people','final_why','final_comms','final_welcome','final_transmit'])}<h2>✍️ Notre phrase manifeste</h2><div class="manifesto-quote">« Ce réseau vit parce que ${esc(manifest.replace(/^ce réseau vit parce que\s*/i,''))} »</div></section>
  <section><h2>Personnes ayant contribué pendant les 40 minutes</h2>${all}</section></div>`}
  $('#previewBtn').addEventListener('click',()=>{$('#previewContent').innerHTML=summaryHtml();$('#previewDialog').showModal()});$('#closePreview').addEventListener('click',()=>$('#previewDialog').close());
  function printSummary(){const old=document.getElementById('printSummary');if(old)old.remove();const print=document.createElement('div');print.id='printSummary';print.className='print-summary';print.innerHTML=summaryHtml();document.body.appendChild(print);document.body.classList.add('printing-summary');const cleanup=()=>{document.body.classList.remove('printing-summary');print.remove();window.removeEventListener('afterprint',cleanup)};window.addEventListener('afterprint',cleanup);setTimeout(()=>window.print(),80)}
  $('#pdfBtn').addEventListener('click',async()=>{const filename=`Atelier2_VivreReseau_${(state.tableName||'table').replace(/[^a-z0-9_-]+/gi,'_')}.pdf`;const result=await window.IntercvlDriveSync?.generateAndSendPdf({atelier:'atelier2',tableName:state.tableName,jsonBackup:state,html:summaryHtml(),statusEl:$('#driveSyncStatus'),filename});if(result?.ok)toast('✅','PDF enregistré','Le PDF a été généré et enregistré directement dans le Drive de l’équipe organisatrice.',true)});

  $('#backupBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Atelier2_${(state.tableName||'table').replace(/[^a-z0-9_-]+/gi,'_')}_sauvegarde.json`;a.click();URL.revokeObjectURL(a.href)});
  $('#restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const fr=new FileReader();fr.onload=()=>{try{state={...emptyState(),...JSON.parse(fr.result)};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));location.reload()}catch{alert("Ce fichier de sauvegarde n'est pas valide.")}};fr.readAsText(f)});
  $('#driveSyncBtn')?.addEventListener('click',()=>{window.IntercvlDriveSync?.send('atelier2',state.tableName,state,$('#driveSyncStatus'))});
  $('#resetAll').addEventListener('click',()=>{if(confirm('Effacer toutes les notes et tous les prénoms de cette table ?')){localStorage.removeItem(STORAGE_KEY);location.reload()}});

  updateRelayPreviews();renderAllContributors();updateTimer();renderManifesto();go(activeStep);
})();
